from pathlib import Path
import argparse as ap

if __name__ == "__main__":
    parser = ap.ArgumentParser()
    parser.add_argument("--output_dir", "-o", required=True)
    args = parser.parse_args()

    with open(Path(args.output_dir).joinpath("store-files.out"), "w") as f:
        f.write(f"Test output generated by {__file__}\n")
