import argparse as ap
import os
from pathlib import Path

if __name__ == "__main__":
    parser = ap.ArgumentParser()
    parser.add_argument("--output_dir", "-o", required=True)
    args = parser.parse_args()

    with open(Path(args.output_dir).joinpath("store-files.out"), "w") as f:
        f.write(f"Inside Python JOB ID = '{os.environ['SLURM_ARRAY_JOB_ID']}'\n")
        f.write(f"Inside Python TASK ID = '{os.environ['SLURM_ARRAY_TASK_ID']}\n")
        f.write(f"Test output generated by {__file__}\n")
